version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
  app:
    image: linaezaidi/projet-pfa
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
