version: '3.8'

services:
  app:
    image: linaezaidi/projet-pfa:latest
    container_name: projet-pfa-container
    ports:
      - "8080:80" # Redirection du port 80 (Docker) vers le port 8080 (local)
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: projet-pfa-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projet_pfa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Redirection pour accéder à la base de données localement
